#!/bin/bash
# Apply the Keycloak realm patch generated by extract-keycloak-patch.py.
#
# Adds the three pieces that pre-2.14 realms are missing:
#   1. display-system-frontend client          → via partial-import.json
#   2. eregistrations client scope             → via client-scope.json
#   3. declarative user-profile attributes     → via user-profile.json
#
# Plus the cross-wiring that's not carried by partial-import:
#   4. attach default OIDC scopes (web-origins, profile, roles, email,
#      eregistrations) to display-system-frontend — without these the token
#      lacks `sub` and ds-backend's log filter crashes
#   5. attach eregistrations as default scope on the 8 backend clients
#   6. grant realm-management roles (view-clients, view-realm, view-users,
#      query-groups, manage-users) to each backend client's service-account
#      user — without these, bpa-backend's publish flow hits 403 on the
#      admin /client-scopes call
#
# Required env vars:
#   KC_URL           https://login.<domain>
#   KC_REALM         realm name (uppercase per eRegistrations convention)
#   KC_ADMIN_USER    master-realm admin user
#   KC_ADMIN_PASS    master-realm admin password
#
# Idempotent — re-running reports [EXISTS]/409 for already-applied changes.

set -euo pipefail

: "${KC_URL:?Set KC_URL}"
: "${KC_REALM:?Set KC_REALM}"
: "${KC_ADMIN_USER:?Set KC_ADMIN_USER}"
: "${KC_ADMIN_PASS:?Set KC_ADMIN_PASS}"

DIR="$(cd "$(dirname "$0")" && pwd)"

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'

echo "Fetching admin token from $KC_URL ..."
TOKEN=$(curl -sf -X POST "$KC_URL/realms/master/protocol/openid-connect/token" \
    -H 'Content-Type: application/x-www-form-urlencoded' \
    -d "client_id=admin-cli" \
    -d "username=$KC_ADMIN_USER" \
    -d "password=$KC_ADMIN_PASS" \
    -d "grant_type=password" \
    | python3 -c 'import json,sys;print(json.load(sys.stdin)["access_token"])')

if [ -z "$TOKEN" ]; then
    echo -e "${RED}Failed to obtain token${NC}"; exit 1
fi
AUTH="Authorization: Bearer $TOKEN"

# ---- 1a. partial import: display-system-frontend client -------------------
echo ""
echo "1a. Partial import (display-system-frontend client)..."
curl -sfS -X POST "$KC_URL/admin/realms/$KC_REALM/partialImport" \
    -H "$AUTH" -H 'Content-Type: application/json' \
    --data-binary "@$DIR/partial-import.json" \
    | python3 -m json.tool || true

# ---- 1b. create eregistrations client scope -------------------------------
echo ""
echo "1b. Create 'eregistrations' client scope..."
SCOPE_STATUS=$(curl -s -o /tmp/kc-scope-resp -w '%{http_code}' \
    -X POST "$KC_URL/admin/realms/$KC_REALM/client-scopes" \
    -H "$AUTH" -H 'Content-Type: application/json' \
    --data-binary "@$DIR/client-scope.json")
case $SCOPE_STATUS in
    201) echo -e "  ${GREEN}[CREATED] eregistrations client scope${NC}" ;;
    409) echo -e "  ${YELLOW}[EXISTS] eregistrations client scope${NC}" ;;
    *)   echo -e "  ${RED}[ERROR $SCOPE_STATUS] $(cat /tmp/kc-scope-resp 2>/dev/null || true)${NC}" ;;
esac

# ---- 1c. attach default scopes to display-system-frontend -----------------
echo ""
echo "1c. Attach default client scopes to display-system-frontend..."
DSFE_UUID=$(curl -sf -H "$AUTH" "$KC_URL/admin/realms/$KC_REALM/clients?clientId=display-system-frontend" \
    | python3 -c 'import json,sys
data=json.load(sys.stdin)
print(data[0]["id"] if data else "")')

if [ -z "$DSFE_UUID" ]; then
    echo -e "  ${RED}display-system-frontend client missing — partial import failed?${NC}"
else
    for scope_name in web-origins profile roles email eregistrations; do
        SID=$(curl -sf -H "$AUTH" "$KC_URL/admin/realms/$KC_REALM/client-scopes" \
            | python3 -c "
import json,sys
data=json.load(sys.stdin)
for s in data:
    if s['name']=='$scope_name':
        print(s['id']); break")
        if [ -z "$SID" ]; then
            echo -e "  ${YELLOW}[SKIP] scope '$scope_name' not in realm${NC}"
            continue
        fi
        STATUS=$(curl -s -o /dev/null -w '%{http_code}' \
            -X PUT "$KC_URL/admin/realms/$KC_REALM/clients/$DSFE_UUID/default-client-scopes/$SID" \
            -H "$AUTH")
        case $STATUS in
            204) echo -e "  ${GREEN}[ADDED] $scope_name${NC}" ;;
            409) echo -e "  ${YELLOW}[EXISTS] $scope_name${NC}" ;;
            *)   echo -e "  ${RED}[ERROR $STATUS] $scope_name${NC}" ;;
        esac
    done
fi

# ---- 2. user profile ------------------------------------------------------
echo ""
echo "2. Update user profile (declarative-user-profile attributes)..."
curl -sfS -X PUT "$KC_URL/admin/realms/$KC_REALM/users/profile" \
    -H "$AUTH" -H 'Content-Type: application/json' \
    --data-binary "@$DIR/user-profile.json" \
    && echo -e "${GREEN}user-profile updated${NC}" \
    || echo -e "${RED}user-profile update failed${NC}"

# ---- 3. attach eregistrations scope to backend clients --------------------
echo ""
echo "3. Attach 'eregistrations' default scope to backend clients..."

SCOPE_ID=$(curl -sf -H "$AUTH" "$KC_URL/admin/realms/$KC_REALM/client-scopes" \
    | python3 -c 'import json,sys;[print(s["id"]) for s in json.load(sys.stdin) if s["name"]=="eregistrations"]')

if [ -z "$SCOPE_ID" ]; then
    echo -e "${RED}eregistrations scope not found — step 1b may have failed${NC}"; exit 1
fi
echo "  eregistrations scope id: $SCOPE_ID"
echo "  (record this id in docker-stack.yml: KEYCLOAK_CLIENT_SCOPE_ID=$SCOPE_ID on bpa-backend)"

ASSIGN_SCOPE_TO="${ASSIGN_SCOPE_TO:-bpa-backend bpa-frontend camunda-client ds-client gdb-client statistics-backend statistics-frontend mcp-eregistrations-bpa}"
for cid in $ASSIGN_SCOPE_TO; do
    CLIENT_UUID=$(curl -sf -H "$AUTH" "$KC_URL/admin/realms/$KC_REALM/clients?clientId=$cid" \
        | python3 -c 'import json,sys
data=json.load(sys.stdin)
print(data[0]["id"] if data else "")')
    if [ -z "$CLIENT_UUID" ]; then
        echo -e "  ${YELLOW}[SKIP] $cid not found${NC}"
        continue
    fi
    STATUS=$(curl -s -o /dev/null -w '%{http_code}' \
        -X PUT "$KC_URL/admin/realms/$KC_REALM/clients/$CLIENT_UUID/default-client-scopes/$SCOPE_ID" \
        -H "$AUTH")
    case $STATUS in
        204) echo -e "  ${GREEN}[ADDED] $cid${NC}" ;;
        409) echo -e "  ${YELLOW}[EXISTS] $cid${NC}" ;;
        *)   echo -e "  ${RED}[ERROR $STATUS] $cid${NC}" ;;
    esac
done

# ---- 4. realm-management roles on backend service accounts ----------------
echo ""
echo "4. Grant realm-management roles to backend service accounts..."
echo "   (fixes 403 on bpa-backend's admin /client-scopes call during publish)"

RM_UUID=$(curl -sf -H "$AUTH" "$KC_URL/admin/realms/$KC_REALM/clients?clientId=realm-management" \
    | python3 -c 'import json,sys
data=json.load(sys.stdin)
print(data[0]["id"] if data else "")')
if [ -z "$RM_UUID" ]; then
    echo -e "  ${RED}realm-management client not found — admin API unavailable?${NC}"; exit 1
fi

ROLE_NAMES=(view-clients view-realm view-users query-groups manage-users)
declare -A ROLE_OBJ
for role in "${ROLE_NAMES[@]}"; do
    obj=$(curl -sf -H "$AUTH" "$KC_URL/admin/realms/$KC_REALM/clients/$RM_UUID/roles/$role" || true)
    [ -n "$obj" ] && ROLE_OBJ[$role]="$obj" || echo -e "  ${YELLOW}role '$role' missing in realm-management — skipping${NC}"
done

BACKEND_CLIENTS="bpa-backend ds-client gdb-client camunda-client statistics-backend"

for cid in $BACKEND_CLIENTS; do
    CLIENT_UUID=$(curl -sf -H "$AUTH" "$KC_URL/admin/realms/$KC_REALM/clients?clientId=$cid" \
        | python3 -c 'import json,sys
data=json.load(sys.stdin)
print(data[0]["id"] if data else "")')
    [ -z "$CLIENT_UUID" ] && { echo -e "  ${YELLOW}[SKIP] $cid not found${NC}"; continue; }
    SA_USER_UUID=$(curl -sf -H "$AUTH" "$KC_URL/admin/realms/$KC_REALM/clients/$CLIENT_UUID/service-account-user" \
        | python3 -c 'import json,sys
data=json.load(sys.stdin)
print(data.get("id",""))')
    [ -z "$SA_USER_UUID" ] && { echo -e "  ${YELLOW}[SKIP] $cid — no service-account user${NC}"; continue; }

    ROLES_JSON='['
    first=1
    for role in "${ROLE_NAMES[@]}"; do
        [ -n "${ROLE_OBJ[$role]:-}" ] || continue
        [ $first -eq 0 ] && ROLES_JSON+=','
        ROLES_JSON+="${ROLE_OBJ[$role]}"
        first=0
    done
    ROLES_JSON+=']'

    STATUS=$(curl -s -o /tmp/kc-role-resp -w '%{http_code}' \
        -X POST "$KC_URL/admin/realms/$KC_REALM/users/$SA_USER_UUID/role-mappings/clients/$RM_UUID" \
        -H "$AUTH" -H 'Content-Type: application/json' \
        -d "$ROLES_JSON")
    case $STATUS in
        204) echo -e "  ${GREEN}[GRANTED] $cid → ${ROLE_NAMES[*]}${NC}" ;;
        409) echo -e "  ${YELLOW}[EXISTS] $cid roles already present${NC}" ;;
        *)   echo -e "  ${RED}[ERROR $STATUS] $cid: $(cat /tmp/kc-role-resp 2>/dev/null || true)${NC}" ;;
    esac
done

echo ""
echo -e "${GREEN}Done.${NC}"
echo ""
echo "Next:"
echo "  1. Mirror generated client-secret UUIDs (from extract-keycloak-patch.py output) into .env"
echo "  2. Add 'KEYCLOAK_CLIENT_SCOPE_ID=$SCOPE_ID' env var to bpa-backend in docker-stack.yml"
echo "  3. Redeploy"
